### ISSUE TITLE
Calendar API: Filter Start date

### ISSUE THREAD

**Issue by andibraeu** [fossasia/api.fossasia.net#34]
Wht do you think?
Is it better to return only events starting at or after the time of your query? I'd like this more.

Optional we can set a start date to also gather events from the past.

**Comment by zyzo** [comment]
@andibraeu what I did to filter events by date time was having two parameters `from` and `to` to limit events by property `DTSTART`. I think it's flexible and up to the users to choose how to use them.

For e.g we can just set `from` to the current time in the API query. A default value `from=now` could be implemented as well. 

Another challenge is how to implement `limit` to work well with `from`, `to` and `sort` to return the results we want. (#23, #32, #33)

**Comment by andibraeu** [comment]
ok, thank you. from=now as default woud be great!

limit I would implement like this: first get all results with filters applied, then sort them and as last step do not return more results than the limit allows

**Comment by zyzo** [comment]
@andibraeu after consideration I think it's best that `now` should be a valid value for parameter `from` (and `to`), but it shouldn't be the default. The reason is : if it's the default, there's no way from filter can be turned off. User could set from to a very old date, but it isn't elegant. So I'll turn it off.

**Comment by andibraeu** [comment]
works
