### ISSUE TITLE
what kind of frontend do we need for a ics parser and merger

### ISSUE THREAD

**Issue by andibraeu** [fossasia/api.fossasia.net#9]
Let's collect ideas. please describe how they could look like

* simple ICS file
* ICS file filtered by categories
* next x events of all communities as HTML list

**Comment by zyzo** [comment]
I propose a community news panel that shows latest/upcoming events, like twitter embed timeline. We could also serve the mixed ICS via an API endpoint, with filters like : 
* category
* country
* since
* until
* recurrent 
* limit
..

I'm not sure of the use case of the rest, but category, since and until are useful to implement the community news panel mentioned above.

**Comment by andibraeu** [comment]
sounds good!

How can we see which community the event belongs to? Does the merge set a category or something like this?

**Comment by zyzo** [comment]
@andibraeu  I don't know if there is a defined ics field for this, but we could always use custom field starting with `X-` to specify event source. I remark that the key of each document in ffSummarizedDir.json https://freifunk.net/map/ffSummarizedDir.json seems like community name. Could we use those keys as unique community identifiers ?

**Comment by andibraeu** [comment]
yes, those are unique identifiers

**Comment by zyzo** [comment]
Perfect. For the community news panel, do you have any reference for the calendar library ? I'm comparing solutions.

**Comment by zyzo** [comment]
the final front-end product is https://github.com/fossasia/timeline.api.fossasia.net
